name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build-test-deploy:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [12.x]
                os: [macos-latest, ubuntu-latest, windows-latest]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cache node modules
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm install
              working-directory: client
            - name: Lint
              run: npm run lint
              working-directory: client
            - name: Build
              run: npm run build
              working-directory: client
            - name: Test
              run: npm run test
              working-directory: client
